
[#aura]
= Using with Neo4j AuraDB

[abstract]
--
This chapter describes considerations around using Neo4j Connector for Apache Spark with link:https://neo4j.com/cloud/aura/[Neo4j AuraDB].
--

== Overview

link:https://neo4j.com/cloud/aura/[Neo4j AuraDB] is a fully managed cloud graph database service.

== Connecting to AuraDB

Connecting to Neo4j AuraDB is similar to connecting to on-premise Neo4j instances, but keep in mind:

* Always use a `neo4j+s://` driver URI when communicating with the cluster in the client application.  The optimal
driver URI is provided by AuraDB itself when you create a database.
* In AuraDB Enterprise consider creating a separate username/password for Spark access; avoid running all processes through the default
`neo4j` account.

== Connecting to AuraDB from Spark on Databricks

AuraDB customers connecting from Databricks may encounter SSL handshake errors due to Databricks' custom Java security settings removing certain cipher support.

See the AuraDB support article link:{url-aura-kbase-databricks}[Connecting to Aura with Databricks] for more information and instructions on how to configure your Databricks cluster to support connections to AuraDB.

== Combining AuraDB and AuraDS

AuraDB is the Neo4j Cloud solution for OLTP processes while AuraDS is designed for computing large-scale graph/ml algorithms in the cloud. With the Neo4j Spark connector you can easily:
* export the data from AuraDB ingesting it in AuraDS
* run GDS graph/ml algorithms over your data in AuraDS
* write the result of the computation back to AuraDB in order to enrich your transactional data
