
[#neo4j_causal_cluster]
= Using with Neo4j Causal Cluster

:description: This chapter describes considerations around using Neo4j Connector for Apache Spark with Neo4j Enterprise Causal Cluster.

== Overview

link:https://neo4j.com/docs/operations-manual/current/clustering/[Neo4j Clustering] is a feature available in
Enterprise Edition, which allows high availability of the database through having multiple database members.

Neo4j Enterprise uses a link:https://neo4j.com/docs/operations-manual/current/clustering/introduction/#causal-clustering-introduction-operational[Primary/Secondary servers]
operational view. Write operations are always processed by the Primary servers only, while reads can be serviced by either Primary servers (link:https://neo4j.com/docs/operations-manual/current/clustering/internals/#causal-clustering-elections-and-leadership[Leaders or Followers]),
or optionally by Read Replicas, which maintain a copy of the database and serve to scale out read operations
horizontally.

== Remote clients

Sometimes there are remote applications that talk to Neo4j via official drivers, that want to use
streams functionality. Best practices in these cases are:

* Always use a `neo4j+s://` driver URI when communicating with the cluster in the client application.